import Foundation
import SwiftUI

// Generated by ChatGPT

struct SampleApp: Hashable {
    let name: String
    let firstMotto: String
    let secondMotto: String
    let color: Color
}

let sampleApps: [SampleApp] = [
    ("QuantumSnap", [
        "Capture moments beyond the ordinary.",
        "Freeze time with a quantum touch.",
    ], (176, 224, 230)), // Pastel Turquoise

    ("AeroAmplify", [
        "Amplifying your experience, one breath at a time.",
        "Soar to new heights with AeroAmplify.",
    ], (255, 182, 193)), // Pastel Pink

    ("CelestialCipher", [
        "Unlock the secrets of the cosmos within.",
        "Journey through the stars with CelestialCipher.",
    ], (173, 216, 230)), // Pastel Blue

    ("LushLagoon", [
        "Immerse yourself in the beauty of tranquility.",
        "Discover serenity at the heart of LushLagoon.",
    ], (152, 251, 152)), // Pastel Green

    ("RapidRipple", [
        "Creating waves of change, one ripple at a time.",
        "Transforming the tide of possibilities.",
    ], (255, 218, 185)), // Pastel Peach

    ("ZenithZoom", [
        "Enhance your perspective, embrace the zenith.",
        "Zoom into clarity with ZenithZoom.",
    ], (240, 230, 140)), // Pastel Khaki

    ("PixelPulse", [
        "Infuse vibrancy into every pixel.",
        "Where pixels dance with life.",
    ], (255, 228, 196)), // Pastel Bisque

    ("SapphireSprint", [
        "Sprint towards brilliance with SapphireSprint.",
        "Unleash the power of deep blue acceleration.",
    ], (173, 216, 230)), // Pastel Blue

    ("TranquilTwist", [
        "Embrace the twist, find tranquility within.",
        "Twist into serenity with TranquilTwist.",
    ], (144, 238, 144)), // Pastel Light Green

    ("EpicEclipse", [
        "Where epic moments eclipse the ordinary.",
        "Step into the shadow of extraordinary experiences.",
    ], (255, 228, 196)), // Pastel Bisque

    ("NovaNectar", [
        "Sip the sweetness of innovation with NovaNectar.",
        "Nourishing creativity, drop by drop.",
    ], (255, 182, 193)), // Pastel Pink

    ("VividVortex", [
        "Where colors converge in a vibrant dance.",
        "Get swept away in the whirlwind of vivid experiences.",
    ], (176, 224, 230)), // Pastel Turquoise

    ("EclipseEcho", [
        "Echoes of moments eclipsed in the EclipseEcho.",
        "Experience the reverberation of extraordinary times.",
    ], (240, 230, 140)), // Pastel Khaki

    ("WhirlwindWaltz", [
        "Dance through the storm of possibilities.",
        "Elegance in motion, embrace the whirlwind waltz.",
    ], (255, 228, 196)), // Pastel Bisque

    ("GloboGlide", [
        "Glide across the globe with GloboGlide.",
        "Seamless journeys, boundless horizons.",
    ], (173, 216, 230)), // Pastel Blue

    ("PinnaclePulse", [
        "Reach the pinnacle with every pulse.",
        "PinnaclePulse: Elevate your rhythm, ascend to greatness.",
    ], (152, 251, 152)), // Pastel Green

    ("ZephyrZoom", [
        "Riding the gentle breeze of clarity.",
        "Zoom into possibilities with the whispering zephyr.",
    ], (144, 238, 144)), // Pastel Light Green

    ("MysticMingle", [
        "Where mysteries intertwine.",
        "Mingle with the mystique, unravel the unknown.",
    ], (218, 112, 214)), // Pastel Orchid

    ("OrbitOpus", [
        "Craft your masterpiece in the OrbitOpus.",
        "OrbitOpus: A symphony of creativity in orbit.",
    ], (255, 218, 185)), // Pastel Peach

    ("PulsePlunge", [
        "Dive into the rhythm of life.",
        "Feel the pulse, embrace the plunge.",
    ], (255, 228, 196)), // Pastel Bisque

    ("SonicSprint", [
        "Racing to the speed of sound.",
        "Feel the sonic boom, embrace the sprint.",
    ], (176, 224, 230)), // Pastel Turquoise

    ("PolarisPulse", [
        "Navigating the stars of possibility.",
        "Sync your pulse with the pulse of Polaris.",
    ], (255, 182, 193)), // Pastel Pink

    ("HarmonyHaven", [
        "Where serenity finds its home.",
        "Dwell in the haven of tranquil harmony.",
    ], (173, 216, 230)), // Pastel Blue

    ("VortexVista", [
        "A panoramic view of endless wonders.",
        "Immerse yourself in the vista of swirling possibilities.",
    ], (152, 251, 152)), // Pastel Green

    ("BlissBlast", [
        "Unleash waves of pure joy.",
        "Experience the bliss, ride the joyful blast.",
    ], (240, 230, 140)), // Pastel Khaki

    ("GalacticGaze", [
        "Fix your eyes on the wonders beyond.",
        "Gaze into the cosmos, explore the galactic mysteries.",
    ], (255, 228, 196)), // Pastel Bisque

    ("SolarSync", [
        "Aligning with the rhythm of the sun.",
        "Sync your energy with the radiant pulse of the sun.",
    ], (218, 112, 214)), // Pastel Orchid

    ("TidalTwirl", [
        "Dancing with the ebb and flow of life.",
        "Twirl with the tides, embrace the tidal dance.",
    ], (255, 218, 185)), // Pastel Peach

    ("OrbitOpus", [
        "Crafting melodies in the celestial sphere.",
        "Compose your opus amidst the orbits of inspiration.",
    ], (144, 238, 144)), // Pastel Light Green

    ("LuminaryLoom", [
        "Weaving threads of brilliance.",
        "Illuminate your path with the loom of luminary threads.",
    ], (255, 228, 196)), // Pastel Bisque

    ("SapphireSprint", [
        "Racing through a sea of brilliance.",
        "Feel the rush, embrace the sprint of sapphire.",
    ], (176, 224, 230)), // Pastel Turquoise

    ("TranquilTwist", [
        "Finding peace in the gentle twists.",
        "Twist into serenity with TranquilTwist.",
    ], (255, 182, 193)), // Pastel Pink

    ("RapidRift", [
        "Navigating through the swift currents of change.",
        "Feel the rapid currents, embark on the rift of transformation.",
    ], (173, 216, 230)), // Pastel Blue

    ("CelestialCraze", [
        "Embracing the cosmic dance of possibilities.",
        "Dance with the cosmos, ride the celestial craze.",
    ], (152, 251, 152)), // Pastel Green

    ("PulsePlunge", [
        "Diving into the rhythm of life.",
        "Feel the pulse, embrace the plunge.",
    ], (240, 230, 140)), // Pastel Khaki

    ("MysticMingle", [
        "Mingling with the mysteries of the unknown.",
        "Mingle with the mystique, unravel the secrets.",
    ], (255, 228, 196)), // Pastel Bisque

    ("QuasarQuest", [
        "Embarking on a cosmic journey of discovery.",
        "Quest for the unknown, explore the cosmic quasars.",
    ], (218, 112, 214)), // Pastel Orchid

    ("EtherealEcho", [
        "Resonating echoes of extraordinary moments.",
        "Experience the ethereal, embrace the echoes of brilliance.",
    ], (255, 218, 185)), // Pastel Peach

    ("ZenithZoom", [
        "Zooming into the highest points of clarity.",
        "Enhance your perspective, embrace the zenith.",
    ], (144, 238, 144)), // Pastel Light Green

    ("LunaLoom", [
        "Weaving moonlit threads of enchantment.",
        "Loom in the glow of Luna, embrace the enchantment.",
    ], (255, 228, 196)), // Pastel Bisque
]
    .map { raw in
        SampleApp(
            name: raw.0,
            firstMotto: raw.1[0],
            secondMotto: raw.1[1],
            color: Color(red: raw.2.0 / 255, green: raw.2.1 / 255, blue: raw.2.2 / 255)
        )
    }
